apiVersion: v1
kind: ConfigMap
metadata:
  name: ezkafka-visualizer-config
  namespace: ezkafka-visualizer
data:
  NODE_ENV: "production"
  PORT: "3700"
  HOSTNAME: "0.0.0.0"
  # Kafka configuration - update these values according to your Kafka setup
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_CLIENT_ID: "ezkafka-visualizer"
