apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ezkafka-visualizer-ingress
  namespace: ezkafka-visualizer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: ezkafka.local  # Change this to your desired hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ezkafka-visualizer-service
            port:
              number: 3700
  # Uncomment the following section if you want to enable TLS
  # tls:
  # - hosts:
  #   - ezkafka.local
  #   secretName: ezkafka-visualizer-tls
